source 'https://rubygems.org'

gem 'rails', '3.2.11'
gem 'pg'
gem 'jquery-rails'
gem 'nokogiri'
gem 'bcrypt-ruby', '3.0.1'
gem 'haml'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :test do
  gem "faker", "~> 1.1.2"
  gem "database_cleaner", "~> 0.9.1"
  gem "launchy", "~> 2.2.0"
  gem 'rb-fsevent', '0.9.1', :require => false
  gem 'growl', '1.0.3'
end

group :development, :test do
  gem "capybara", "~> 2.0.2"
  gem "rspec-rails", "~> 2.12.2"
  gem "factory_girl_rails", "~> 4.2.0"
  gem "guard-rspec", "~> 2.4.0"
  gem 'pry-rails'
  gem 'pry-debugger'
  gem 'pry-stack_explorer'
  gem 'annotate'
  gem 'quiet_assets'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
end